// Generated by CoffeeScript 1.3.1
(function() {

  Ext.define('Lizard.popup.FeatureInfo', {
    extend: 'Ext.form.Panel',
    startValue: null,
    bodyStyle: 'padding:5px 5px 0',
    defaults: {
      anchor: '100%'
    },
    width: 300,
    init_background: null,
    statics: {
      show: function(records, workspaceitem) {
        var data, html, record, tpl;
        record = records[0];
        data = [];
        Ext.Object.each(record.data, function(key, value) {
          return data.push({
            key: key,
            value: value
          });
        });
        tpl = new Ext.XTemplate('<div class="lizard">', '<h2>Kaartlaag: {layer_name}</h2>', '<table>', '<tpl for="fields">', '<tr><td>{key}</td><td>{value}</td></tr>', '</tpl></table></div>');
        html = tpl.applyTemplate({
          layer_name: workspaceitem.get('title'),
          fields: data
        });
        return Ext.create('Ext.window.Window', {
          title: 'Info',
          popup_type: 'feature_info',
          constrainHeader: true,
          items: [
            {
              xtype: 'panel',
              width: 400,
              html: html
            }
          ]
        }).show();
      }
    },
    items: [{}]
  });

}).call(this);
